### ISSUE TITLE
nci_usage

### ISSUE THREAD

**Issue by ccarouge** [coecms/ncimonitor#20]
The user needs to input a filesystem for nci_usage to work but this isn't handled properly. 
```nciusage -P w42 --percent
Traceback (most recent call last):
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.01/bin/nciusage", line 12, in <module>
    sys.exit(main())
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis3-19.01/lib/python3.6/site-packages/ncimonitor/nci_usage.py", line 59, in main
    if args.measure == 'inodes':
AttributeError: 'Namespace' object has no attribute 'measure'
```

Either:

- handle the error and exit gracefully

- work like `ncimonitor` and return the data for both short and gdata if nothing is specified.

**Comment by aidanheerdegen** [comment]
Command line options should be modified to be consistent with `ncimonitor`

```
nciusage
```
would spit out `short` and `gdata` usage To specify only one storage point
```
nciusage --short
```
and to specify inodes instead
```
nciusage --short --inodes
```
