### ISSUE TITLE
gdata not working with delta?

### ISSUE THREAD

**Issue by ccarouge** [coecms/ncimonitor#7]
Maybe I'm doing something stupid but here is what I've done and the error:
[ccc561@raijin2 tmp]$ ncimonitor -P w42 --gdata --pdf -d   
       
Traceback (most recent call last):
  File "/projects/access/apps/ncimonitor/0.2/bin/ncimonitor", line 330, in <module>
    plot_storage(db,'gdata',year,quarter,datafield,args.showtotal,cutoff,users,args.pdf)
  File "/projects/access/apps/ncimonitor/0.2/bin/ncimonitor", line 142, in plot_storage
    plot_dataframe(dp, type=type, ylabel=ylabel, title=title, cutoff=cutoff, ideal=ideal, outfile=outfile, sort=sort, delta=args.delta)
  File "/projects/access/apps/ncimonitor/0.2/bin/ncimonitor", line 184, in plot_dataframe
    if sort: sort_table_by_last_row(df)
  File "/projects/access/apps/ncimonitor/0.2/bin/ncimonitor", line 83, in sort_table_by_last_row
    df.sort_values(df.last_valid_index(), axis=1, inplace=True, ascending=False)
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis27/lib/python2.7/site-packages/pandas/core/frame.py", line 3786, in last_valid_index
    return self.index[self.count(1) > 0][-1]
  File "/g/data3/hh5/public/apps/miniconda3/envs/analysis27/lib/python2.7/site-packages/pandas/core/indexes/datetimelike.py", line 271, in __getitem__
    val = getitem(key)
IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by aidanheerdegen** [comment]
This was an issue with there being no change to any storage in the quarter. This is rare, but should be captured and no error thrown.

Needs fixing.

**Comment by aidanheerdegen** [comment]
This errors:
```ncimonitor -P w42 --gdata --delta -p 2017.q3```
This does not:
```ncimonitor -P w42 --gdata --delta -p 2017.q4```

**Comment by aidanheerdegen** [comment]
Fixed with https://github.com/coecms/ncimonitor/commit/1cd9fad9c41984be7c2d179559570fb014660272
